name: test

on: [push]

jobs:
  build:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}

      - name: install deps
        run: npm i

      - name: install mpx cli
        run: npm i -g @mpxjs/cli

      - name: test basic project
        run: node __test__/test-basic.js

      - name: test cross project
        run: node __test__/test-cross.js

      - name: test cross web project
        run: node __test__/test-cross-web.js

      - name: test plugin project
        run: node __test__/test-plugin.js

      - name: test cloud project
        run: node __test__/test-cloud.js

      - name: test ts project
        run: node __test__/test-ts.js
